# -*- coding: utf-8 -*-
"""vennela.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hTs1EzW0sM_RGpH0SE2vqBEwNhFuhO71
"""


# Import necessary libraries
import streamlit as st
from qiskit import QuantumCircuit
from qiskit_aer import Aer
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

st.set_page_config(page_title="Quantum Teleportation ML App", layout="centered")

st.title("🧠 Quantum Teleportation + ML Visualization App")
st.write("This app simulates quantum teleportation and classifies Bob’s qubit using a Random Forest model.")

# Quantum teleportation simulation function
def quantum_teleportation_simulation():
    qc = QuantumCircuit(3, 3)
    qc.h(0)
    qc.cx(1, 2)
    qc.h(1)
    qc.cx(0, 1)
    qc.h(0)
    qc.measure([0, 1], [0, 1])
    qc.cx(1, 2)
    qc.cz(0, 2)
    qc.measure(2, 2)

    simulator = Aer.get_backend('qasm_simulator')
    job = execute(qc, simulator, shots=1000)
    result = job.result()
    counts = result.get_counts()
    return counts

# Run when button is clicked
if st.button("Run Quantum Teleportation"):
    counts = quantum_teleportation_simulation()

    # Prepare data for ML
    X = []
    y = []

    for state, count in counts.items():
        features = list(map(int, list(state[::-1])))
        X.extend([features] * count)
        y.extend([features[2]] * count)

    X = np.array(X)
    y = np.array(y)
    X_train, X_test, y_train, y_test = train_test_split(X[:, :2], y, test_size=0.3, random_state=42)

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    st.success(f"🎯 Random Forest Accuracy: {accuracy * 100:.2f}%")

    # Plot result
    st.subheader("📊 Quantum Teleportation Output (Bob's Qubit)")
    fig, ax = plt.subplots()
    plot_histogram(counts, ax=ax)
    st.pyplot(fig)
